spring:
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        generate_statistics: false

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain

logging:
  level:
    com.messmanagement: WARN
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

